### ISSUE TITLE
I find that it can't achieve the target of finding corner from Line 58 to 61 in EdgeDetector.cpp. Because the judgment doesn't work.

### ISSUE THREAD

**Issue by 2897035088** [meiyy/EllDet#1]

**Comment by meiyy** [comment]
Yes, you're right. Code L37-L63 in "EdgeDetector.cpp" is no longer in use. 'corner' is exactly a copy of 'image'. I have updated the code.
There are still many redundant "clone" operations that may affect the efficiency, but I have no time to deal with it for now. You may optimize it yourself.

**Comment by 2897035088** [comment]
Ok. Thanks very much for your source code you provided!

**Comment by 2897035088** [comment]
您好，我看您的文章对比了一些算法，虽然我也找到了一些，但我代码能力有点不行，没法将他们的代码运行起来。所以能冒昧地问一下，您能将您的那些对比算法分享一下吗？如果这些代码您还保留着和您愿意分享给我的话，我将非常感激您的。如果有机会的话，我们可以通过邮箱(2897035088@qq.com)或者微信(13127130083)沟通。
